### ISSUE TITLE
执行跳错啊，请问大佬如何解决

### ISSUE THREAD

**Issue by justincnn** [zhaoboy9692/qccspider#6]
/usr/local/bin/python3.8 /Users/justin/Downloads/qccspider-master/getnewdata.py
Traceback (most recent call last):
  File "/Users/justin/Downloads/qccspider-master/getnewdata.py", line 19, in <module>
    device_id, tim, sign, header = more_get_token()
  File "/Users/justin/Downloads/qccspider-master/common/utils.py", line 93, in more_get_token
    access_token = eval(res.text).get('result').get('access_token')
  File "<string>", line 1, in <module>
NameError: name 'null' is not defined

**Comment by hyp530** [comment]
是不是不能用了？
